language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-21.1.2

    # The SDK version used to compile your project
    - android-21

    # Additional components
    - addon-google_apis-google-21
    - extra-google-google_play_services
    - extra-google-play_services_maps
    - extra-google-play_services_location

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-21
script: ./gradlew build
